name: medical_app
description: تطبيق طبي متكامل مع مكالمات فيديو، QR Code و Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase Core & Auth
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # Notifications & Messaging
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1

  # Storage & Media
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  file_picker: ^8.1.6

  # Video Call (Agora)
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1

  # QR & Scanning
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0

  # PDF & Printing & Files
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.2
  share_plus: ^10.1.3

  # Calendar
  table_calendar: ^3.1.2

  # Utilities & State Management
  provider: ^6.1.2
  uuid: ^4.5.1
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5

  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - assets/images/
