name: medical_app
description: تطبيب طبي متكامل مع مكالمات فيديو، QR Code و Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  firebase_storage: ^12.3.7

  # Media
  image_picker: ^1.1.2
  file_picker: ^8.1.6

  # Video Call
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1

  # QR
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0

  # Files
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.2
  share_plus: ^10.1.3

  # State Management
  provider: ^6.1.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  
  # فك التعليق إذا أضفت مجلد assets
  # assets:
  #   - assets/images/
  #   - assets/fonts/Cairo-Regular.ttf
  #   - assets/fonts/Cairo-Bold.ttf

# إعدادات الترجمة
flutter_gen:
  output: lib/l10n/generated
